export const PREDEFINED_OPTIONS = {
  countries: [
    "United States",
    "Canada",
    "United Kingdom",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Australia",
    "Japan",
    "China",
    "India",
    "Brazil",
    "Mexico",
    "Russia",
    "South Africa",
    "Nigeria",
    "Egypt",
    "Argentina",
    "Chile",
    "Netherlands",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Switzerland",
    "Austria",
    "Belgium",
    "Portugal",
    "Greece",
    "Turkey",
    "South Korea",
    "Thailand",
    "Vietnam",
    "Indonesia",
    "Malaysia",
    "Singapore",
    "Philippines",
    "New Zealand",
    "Ireland",
    "Poland",
    "Czech Republic",
    "Hungary",
    "Romania",
    "Bulgaria",
    "Croatia",
    "Ukraine",
    "Israel",
    "Saudi Arabia",
    "UAE",
    "Qatar",
    "Kuwait",
    "Morocco",
    "Kenya",
    "Ghana",
    "Ethiopia",
    "Tanzania",
    "Uganda",
    "Zimbabwe",
    "Botswana",
    "Namibia",
    "Zambia",
    "Madagascar",
    "Mauritius",
    "Seychelles",
    "Peru",
    "Colombia",
    "Venezuela",
    "Ecuador",
    "Bolivia",
    "Uruguay",
    "Paraguay",
    "Costa Rica",
    "Panama",
    "Guatemala",
    "Honduras",
    "Nicaragua",
    "El Salvador",
    "Dominican Republic",
    "Jamaica",
    "Trinidad and Tobago",
    "Barbados",
    "Bahamas",
    "Cuba",
    "Haiti",
    "Puerto Rico",
  ],
  usStates: [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  cities: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Kansas City",
    "Long Beach",
    "Mesa",
    "Atlanta",
    "Colorado Springs",
    "Virginia Beach",
    "Raleigh",
    "Omaha",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Wichita",
    "New Orleans",
    "Arlington",
  ],
  industries: [
    "Technology",
    "Healthcare",
    "Finance",
    "Education",
    "Manufacturing",
    "Retail",
    "Construction",
    "Transportation",
    "Energy",
    "Agriculture",
    "Entertainment",
    "Hospitality",
    "Real Estate",
    "Consulting",
    "Marketing",
    "Legal",
    "Non-profit",
    "Government",
    "Telecommunications",
    "Automotive",
    "Aerospace",
    "Pharmaceuticals",
    "Food & Beverage",
    "Fashion",
    "Sports",
    "Media",
    "Insurance",
    "Banking",
    "E-commerce",
    "Software Development",
  ],
  jobTitles: [
    "Software Engineer",
    "Product Manager",
    "Data Scientist",
    "UX Designer",
    "Marketing Manager",
    "Sales Representative",
    "Project Manager",
    "Business Analyst",
    "DevOps Engineer",
    "Quality Assurance",
    "Customer Success Manager",
    "Human Resources",
    "Financial Analyst",
    "Operations Manager",
    "Content Writer",
    "Graphic Designer",
    "Account Manager",
    "Consultant",
    "Research Analyst",
    "Executive Assistant",
    "IT Support",
    "Database Administrator",
    "Network Engineer",
    "Security Analyst",
    "Mobile Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Machine Learning Engineer",
    "Cloud Architect",
  ],
  departments: [
    "Engineering",
    "Marketing",
    "Sales",
    "Human Resources",
    "Finance",
    "Operations",
    "Customer Support",
    "Product",
    "Design",
    "Legal",
    "IT",
    "Research & Development",
    "Quality Assurance",
    "Business Development",
    "Administration",
    "Procurement",
    "Logistics",
    "Manufacturing",
    "Compliance",
    "Strategy",
  ],
  educationLevels: [
    "High School Diploma",
    "Associate Degree",
    "Bachelor's Degree",
    "Master's Degree",
    "Doctoral Degree",
    "Professional Degree",
    "Trade School Certificate",
    "Some College",
    "No Formal Education",
  ],
  currencies: [
    "USD - US Dollar",
    "EUR - Euro",
    "GBP - British Pound",
    "JPY - Japanese Yen",
    "CAD - Canadian Dollar",
    "AUD - Australian Dollar",
    "CHF - Swiss Franc",
    "CNY - Chinese Yuan",
    "SEK - Swedish Krona",
    "NZD - New Zealand Dollar",
    "MXN - Mexican Peso",
    "SGD - Singapore Dollar",
    "HKD - Hong Kong Dollar",
    "NOK - Norwegian Krone",
    "KRW - South Korean Won",
    "TRY - Turkish Lira",
    "RUB - Russian Ruble",
    "INR - Indian Rupee",
    "BRL - Brazilian Real",
    "ZAR - South African Rand",
  ],
  languages: [
    "English",
    "Spanish",
    "French",
    "German",
    "Italian",
    "Portuguese",
    "Russian",
    "Chinese (Mandarin)",
    "Japanese",
    "Korean",
    "Arabic",
    "Hindi",
    "Dutch",
    "Swedish",
    "Norwegian",
    "Danish",
    "Finnish",
    "Polish",
    "Czech",
    "Hungarian",
    "Romanian",
    "Bulgarian",
    "Greek",
    "Turkish",
    "Hebrew",
    "Thai",
    "Vietnamese",
    "Indonesian",
    "Malay",
    "Tagalog",
  ],
  timeZones: [
    "UTC-12:00 - Baker Island",
    "UTC-11:00 - American Samoa",
    "UTC-10:00 - Hawaii",
    "UTC-09:00 - Alaska",
    "UTC-08:00 - Pacific Time",
    "UTC-07:00 - Mountain Time",
    "UTC-06:00 - Central Time",
    "UTC-05:00 - Eastern Time",
    "UTC-04:00 - Atlantic Time",
    "UTC-03:00 - Argentina",
    "UTC-02:00 - South Georgia",
    "UTC-01:00 - Azores",
    "UTC+00:00 - London",
    "UTC+01:00 - Central Europe",
    "UTC+02:00 - Eastern Europe",
    "UTC+03:00 - Moscow",
    "UTC+04:00 - Dubai",
    "UTC+05:00 - Pakistan",
    "UTC+06:00 - Bangladesh",
    "UTC+07:00 - Thailand",
    "UTC+08:00 - China",
    "UTC+09:00 - Japan",
    "UTC+10:00 - Australia East",
    "UTC+11:00 - Solomon Islands",
    "UTC+12:00 - New Zealand",
  ],
  months: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  daysOfWeek: [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ],
  yesNoOptions: ["Yes", "No"],
  satisfactionLevels: [
    "Very Satisfied",
    "Satisfied",
    "Neutral",
    "Dissatisfied",
    "Very Dissatisfied",
  ],
  frequencies: ["Never", "Rarely", "Sometimes", "Often", "Always"],
  priorities: ["Low", "Medium", "High", "Critical"],
  sizes: ["Extra Small", "Small", "Medium", "Large", "Extra Large"],
};

export const PREDEFINED_CATEGORIES = [
  { label: "Geographic", options: ["countries", "usStates", "cities"] },
  {
    label: "Professional",
    options: ["industries", "jobTitles", "departments"],
  },
  { label: "Personal", options: ["educationLevels", "languages"] },
  { label: "Technical", options: ["currencies", "timeZones"] },
  { label: "Time & Date", options: ["months", "daysOfWeek"] },
  {
    label: "Common Responses",
    options: [
      "yesNoOptions",
      "satisfactionLevels",
      "frequencies",
      "priorities",
      "sizes",
    ],
  },
];

// Utility functions for importing data
export const parseCSV = (csvText: string): string[] => {
  const lines = csvText.trim().split("\n");
  const options: string[] = [];

  lines.forEach((line) => {
    // Handle both comma-separated and single column CSV
    const values = line.split(",").map((val) => val.trim().replace(/"/g, ""));
    options.push(...values.filter((val) => val.length > 0));
  });

  return [...new Set(options)]; // Remove duplicates
};

export const parseJSON = (jsonText: string): string[] => {
  try {
    const parsed = JSON.parse(jsonText);

    // Handle different JSON structures
    if (Array.isArray(parsed)) {
      return parsed
        .map((item) =>
          typeof item === "string"
            ? item
            : typeof item === "object" && item.label
            ? item.label
            : typeof item === "object" && item.name
            ? item.name
            : typeof item === "object" && item.value
            ? item.value
            : String(item)
        )
        .filter((item) => item.length > 0);
    }

    // If it's an object, try to extract values
    if (typeof parsed === "object" && parsed !== null) {
      const values = Object.values(parsed);
      if (values.every((val) => typeof val === "string")) {
        return values as string[];
      }
    }

    throw new Error("Invalid JSON structure");
  } catch (error) {
    throw new Error("Invalid JSON format");
  }
};


